#!/system/bin/sh
#
# Load any extra modules

MODULES="ax8netfilter.ko x_tables.ko ip_tables.ko iptable_filter.ko nf_conntrack.ko xt_multiport.ko xt_state.ko nf_defrag_ipv4.ko nf_conntrack_ipv4.ko nf_nat.ko iptable_nat.ko ipt_MASQUERADE.ko"

for i in $MODULES
do
    insmod /system/lib/modules/netfilter/$i >/dev/null 2>&1
done


MODULES="dm-mod.ko dm-crypt.ko twofish_common.ko twofish.ko"

for i in $MODULES
do
    insmod /system/lib/modules/$i >/dev/null 2>&1
done

# mddi is device specific
case `getprop ro.product.device` in
shakira)
    insmod /system/lib/modules/mddi.ko device=1 >/dev/null 2>&1
;;
robyn)
    insmod /system/lib/modules/mddi.ko device=2 >/dev/null 2>&1
;;
mimmi)
    insmod /system/lib/modules/mddi.ko device=3 >/dev/null 2>&1
;;
esac

exit 0

