#!/system/xbin/sh

	# remount rootfs rw
	mount -o remount,rw rootfs /
	chmod 0777 /dev -R
	chown 0.2000 /dev/oncrpc -R
	cd /
	rm init*
	rm logo.rle
	rm default.prop
	tar -xf /system/bin/boot.tar
  #nobodyAtall - Fix 
	mkdir -p /cm
	cd /cm
	tar -xf /system/bin/boot.tar
	sync
	# Umount /system, data and cache
	umount -l /dev/block/mtdblock0
	umount -l /dev/block/mtdblock1
	umount -l /dev/block/mtdblock2
	umount -l /dev/block/mtdblock3
	rmdir /system /data /cache /mnt
  #Mount /system to /cm/system
	/sbin/mount_system
	sleep 2
	chroot /cm /init	
